.Dd April 27, 2026
.Dt MUNG 1
.Os
.Sh NAME
.Nm mung
.Nd file editor using filters
.
.
.Sh SYNOPSIS
.Nm
.  Ar file
.Nm
.  Fl -destroy Ar files
.Nm
.  Fl -gc
.
.
.Sh DESCRIPTION
.Nm
is a file editor that uses Unix filters
to modify a file.
It is used to display, modify and
otherwise manipulate text files.
.
.Pp
If invoked with a
.Ar file
argument, then a copy of
.Ar file
is read into the buffer.
Changes are made to this copy and not directly to
.Ar file
itself.
Upon quitting
.Nm ,
any changes not explicitly saved with a
.Cm w
command are preserved until
.Nm
is re\-run on the same file.
.
.Nm ,
rather than fiddling with individual lines or
characters, passes the entire file through a series of shell filters.
The results of each filer are saved
in a history directory along with metadata
that allows reconstruction of how the munging was done.
The histories
are kept in a history repository.
.Pp
The commands allow the creation of a tree rather than just a sequence of
states, and it is possible to display and move around the tree of states,
creating new states at any point.
A state can be written back to the
original file or to any other file.
An ordinary interactive editor can
be run on a state to create a new state, and it is also possible for a
new state to be created by reading in an existing file.
.Pp
States can be given a unique tag and a textual description, and its
possible to display the whole tree or the metadata of a single state,
and to page through the file associated with a particular state.
.Pp
Finally, a shell script that transforms the initial state into the
current state can be written out.
This script can be run outside mung
to transform any file into any other file.
.Pp
.Pp
Unlike such line editors as
.Nm ed
or
.Nm ex ,
.Nm
operates on the whole buffer using a shell filter
such as
.Nm awk ,
.Nm tr ,
or
.Nm sed .
Commands are read from the standard input and
executed to manipulate the contents of the editor buffer.
A typical command might look like
.
.Pp
.Bl -item -offset indent
.      Cm sed "s\&/ Ar old \&/ Ar new Nm \&/g"
.El
.
.Pp
which uses
.Nm sed
to replace all occurrences of the string
.Ar old
with
.Ar new .
.
.Pp
In general,
.Nm
commands consist of a single word, which may be abbreviated
to its first letter, and (where relevant) following text,
known collectively as \(dqthe argument\(dq, separated from
the command word by whitespace.
Exceptionally, the
.Cm destroy
command may not be abbreviated, and the
.Cm |
and
.Cm !
commands do not require following whitespace.
.Sh OPTIONS
The following command-line options are recognized:
.
.Bl -tag -width indent
.  It Fl -destroy Ar files
Destroy the named files as if by the
.Cm destroy
command.
.  It Fl -gc
Run the garbage collector, which looks for
state directories that are no longer connected
with any files, or with the wrong files.
See below.
.  It Fl -help
Display help, then exit.
.
.  It Fl -version
Print version information, then exit.
.
.Sh COMMANDS
All
.Nm
commands can be given using either words or single characters, though
some require additional parameters. If a command extends
over several lines, then each line except for the last must be terminated
with a
.Cm \e
(backslash).
.
.Pp
Only one command per line is allowed.
.Pp
An interrupt (typically
.Sm off
.No \&< Cm Ctrl No \&>\&+ Cm C No )
.Sm on
has the effect of aborting the current command
and returning the editor to command mode.
.
.Pp
.Nm
recognizes the following commands: 
.
.Bl -tag -width indent
.  It Cm "a[ll]"
Displays a single line describing each of the states.
The tree structure is shown by indentation.
.
.  It Cm "b[ack]"
Return to the state from which the last
.Cm jump
or
.Cm undo
command was issued.
.
.  It Cm "d[escribe]" Ar text
Attaches
.Ar text
as a description of the current state.
.
.  It Cm "destroy"
Destroy the entire history and terminate
.Nm .If the current state has not been written,
this command must be given twice in a row
to prevent unintentional loss.
.
.  It Cm "e[dit]"
Run an editor on the buffer.
Creates a new state and makes it the current state.
.Pp
The editor is specified by the environment variable
.Ev VISUAL ,
or if that is not set, by
.Ev EDITOR .
If that is not set either, then
.Xr vim 1
is used.
.
.  It Cm "[jump]" Ar number/tag
Switch to the state identified by
.Ar number
or
.Ar tag .
Note that the command need not be present.
.
.  It Cm "h[elp]" Ar command
Display the list of commands and a brief explanation of each.
If 
.Ar command
is specified, give help for that command.
.  It Cm "m[ung]"
Write a script of shell commands
that when executed will transform
the standard input and write the result
to the standard output,
after performing all the steps specified by
.Cm \&|
commands,
.Cm "e[dit]"
commands, and
.Cm "r[ead]"
commands to accomplish the whole transformation.
.Pp
Note that in the case of an
edit command, an editor
(not necessarily the original editor)
will be run and the user must repeat
whatever was originally done using it
to get to the next state.
Read commands will take their input from the originally named file.
.
.  It Cm "p[age]" Ar command
View the contents of the current state
using the specified pager.
The pager should not make any changes to the state.
The default pager is PAGER, or failing that
.Xr less 1 .
.
.  It Cm "q[uit]"
Quits
.Nm
unconditionally. 
All states are preserved.
.
.  It Cm "r[ead]" Ar file
The contents of
.Ar file
are read into the buffer, replacing everything.
Creates a new state and makes it the current state.
.
.  It Cm "s[how]"
Shows all available information about the
current state, except for the actual contents
of the buffer.
.
.  It Cm "t[ag]" Ar tag
Specify a
.Ar tag
that identifies the current state.
If another state has that tag, it is revoked.
.
.  It Cm "u[ndo]"
Switch to the state from which the current state was created.
.
.  It Cm "w[rite]" Ar file
Writes the current state to
.Ar file
without changing it.
.
.  It Cm \&| Ar command
Filters the buffer using the shell command
.Ar command .
Creates a new state and makes it the current state.
This is the most important command.
.Pp
If the line ends in a backslash,
prompt for more lines until
a line not ending in a backslash is read.
.Pp
Text within braces represents the number or tag of a state.
It is replaced by the name of the file holding that state.
.
.  It Cm \&! Ar command
Executes
.Ar command
without changing the history or the current state.
.
.Be
.Sh ENVIRONMENT
The environment variable
.Ev MUNG_REPOSITORY
is the absolute pathname of the directory where all the
 repository directories for this user are kept.
The default value is $XDG_STATE_HOME/mung,
or failing that, $HOME/.local/share/mung.
.Pp
The environment variable
.Ev VISUAL
is the program used by the
.Cm "e[dit]"
command.
.Pp
The environment variable
.Ev EDITOR
is used if
.Ev VISUAL
is not set.
.Pp
The environment variable
.Ev PAGER
is the program used by the
.Cm "p[age]"
command.
.Pp
The environment variable
.Ev SHELL
is used as the shell to run commands.
.Sh FILES
.
The subdirectories of the repository directory
are named after the device and inode numbers
of the files being edited.
This provides a stable identity, even if the file
being processed gets renamed.
Each directory contails the following files:
.Bl -tag -width "0, 1, 2, ..." -compact
.It Pa pathname
the absolute pathname of the file being edited
.It Pa current
the number of the current state
.It Pa state.json
a JSON array representing all the states and
their various properties
.It Pa "0, 1, 2, ..."
the contents of each state
.Be
.
.Sh EXIT STATUS
.Ex -std
.
.
.Sh SEE ALSO
.Xr awk 1 ,
.Xr cat 1 ,
.Xr cmp 1 ,
.Xr comm 1 ,
.Xr cut 1 ,
.Xr datamash 1 ,
.Xr diff 1 ,
.Xr ed 1 ,
.Xr expand 1 ,
.Xr fmt 1 ,
.Xr fold 1 ,
.Xr grep 1 ,
.Xr head 1 ,
.Xr jq 1 ,
.Xr less 1 ,
.Xr more 1 ,
.Xr most 1 ,
.Xr nl 1 ,
.Xr paste 1 ,
.Xr perlrun 1
(especially the one-liners),
.Xr sed 1 ,
.Xr shuf 1 ,
.Xr sort 1 ,
.Xr tac 1 ,
.Xr tail 1 ,
.Xr tee 1 ,
.Xr tr 1 ,
.Xr uniq 1 ,
.Xr vi 1
.
.
.Sh BUGS
In this preliminary version, the
.Cm mung
command is not implemented.
