#!env python

from os import getenv, stat, mkdir
from os.path import join
from sys import argv

states = {}		# map from id to state dictionaries
dependencies = {}	# map from id to list of ids on which it depends
stack = []		# stack of ids for jumps and returns
current = 0		# current state id

all_states = getenv("MUNG_ALL_STATES", "/var/tmp")
editor = getenv("VISUAL", getenv("EDITOR, "vi"))
pager = getenv("PAGER", "less")
state_dir = None

def main():
    global all_states
    state_dir = filename2dir(argv[1])

def name2dir(name):
    try:
	result = stat(argv[1])
    except FileNotFoundException:
        return None
   return join(all_states, str(result.st_ino)

